### ISSUE TITLE
[Mega Tracking] - Align SSZ to latest spec

### ISSUE THREAD

**Issue by 0xKiwi** [prysmaticlabs/go-ssz#3]
This PR tracks the overall progress of aligning our implementation of SSZ to the [dev branch](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md) of the spec.

- [x] 💎  **Move completed SSZ work in [`spec-v0.6` branch](https://github.com/prysmaticlabs/prysm/commits/spec-v0.6/shared/ssz) to this repo.** 💎 | #6 
  (`master` branch was migrated rather than `spec-v0.6` branch)
    - [x] `selfSignedRoot`
    - [x] `truncate_last`

- [x] 💎  **[Constants](sszChunkSize)**  💎| #4
    - [x] Rename `sszChunkSize` to `bytesPerChunk`
    - [x] Add `bytesPerLengthOffset`
    - [x] Add `bitsPerByte`

- [x] 💎  **Create new [helper functions](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md#merkleization)** 💎 | #5
    - [x] `pack`
    - [x] `merkleize`
    - [x] `mix_in_length`
    - [x] `mix_in_type`

- [x] 💎  **Modifications to encoding [composite types](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md#vectors-containers-lists-unions)**  💎
    - [x] vectors 
    - [x] containers
    - [x] lists
    - [x] unions

- [x] 💎  **Modifications to existing helper functions** 💎
    - [x] Add support to [encode null](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md#null)

- [x] 💎  **Modifications to merkleHash** 💎
    - [x] move packing of inputs into `BYTES_PER_CHUNK` to a new `pack` function.
    - [x] Rename from `merkleHash` to `merkleize`

- [x] 💎  **Update TreeHash to the [new definition](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md#merkleization)** 💎

**Comment by rauljordan** [comment]
Resolved
