### ISSUE TITLE
Align Go-SSZ to Latest, v0.8 Ethereum Specification

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/go-ssz#34]
This is a tracking issue to ensure our go-ssz implementation is up to date with the latest v0.8 specification. This specification has been tagged as frozen by the Ethereum researchers, meaning there will be no future feature additions or removals, and only critical bug fixes infrequently.

- [x] Add bitvector and bitlist support for marshaling/unmarshaling (fixed-size and variable-size lists of booleans)
- [x] Add hash tree root support for bitvector and bitlists
- [x] Enforce max capacity for lists
- [x] Add an IsEmpty function which returns true if an object equals the default value of an instance of its type
